### ISSUE TITLE
Retrieving the version throws exception

### ISSUE THREAD

**Issue by bmuschko** [kpelykh/docker-java#52]
Retrieving the Docker version using the `version()` method throws the following exception:

```
Caused by: org.codehaus.jackson.map.exc.UnrecognizedPropertyException: Unrecognized field "ApiVersion" (Class com.kpelykh.docker.client.model.Version), not marked as ignorable
 at [Source: com.sun.jersey.client.apache4.ApacheHttpClient4Handler$HttpClientResponseInputStream@1206cda0; line: 1, column: 16] (through reference chain: com.kpelykh.docker.client.model.Version["ApiVersion"])
    at org.codehaus.jackson.map.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:53)
    at org.codehaus.jackson.map.deser.StdDeserializationContext.unknownFieldException(StdDeserializationContext.java:267)
    at org.codehaus.jackson.map.deser.std.StdDeserializer.reportUnknownProperty(StdDeserializer.java:649)
    at org.codehaus.jackson.map.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:635)
    at org.codehaus.jackson.map.deser.BeanDeserializer.handleUnknownProperty(BeanDeserializer.java:1355)
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:717)
    at org.codehaus.jackson.map.deser.BeanDeserializer.deserialize(BeanDeserializer.java:580)
    at org.codehaus.jackson.map.ObjectMapper._readValue(ObjectMapper.java:2695)
    at org.codehaus.jackson.map.ObjectMapper.readValue(ObjectMapper.java:1308)
    at org.codehaus.jackson.jaxrs.JacksonJsonProvider.readFrom(JacksonJsonProvider.java:419)
    at com.sun.jersey.json.impl.provider.entity.JacksonProviderProxy.readFrom(JacksonProviderProxy.java:139)
    at com.sun.jersey.api.client.ClientResponse.getEntity(ClientResponse.java:634)
    ... 63 more
```

This is my Docker environment:

```
$ docker version
Client version: 0.10.0
Client API version: 1.10
Go version (client): go1.2.1
Git commit (client): dc9c28f
Server version: 0.10.0
Server API version: 1.10
Git commit (server): dc9c28f
Go version (server): go1.2.1
Last stable version: 0.11.1, please update docker
```

**Comment by marcuslinke** [comment]
Hi. It should work with the latest SNAPSHOT now. Could you validate and close the issue please? Thanks.

**Comment by bmuschko** [comment]
Thanks, that works. When are you expecting to publish the final version?
